### PR TITLE
Multiple changes: Multithreading, one click load, remembers path, cleanup

### PR DESCRIPTION
**Pull request by Jamedjo**
- Uses Bass/Rhythm/Lead path to select a sensible track on song change
- Can open disk song list from steam folder
- Minor Style cleanup
- Bugfixes, but they might be because I use .Net 4.0

I don't have .Net 4.5 as I haven't touched C# in a couple of years so I've also made a few changes on a Net4.0 branch which I keep rebasing onto master.

I can split into separate pull requests if you only want some of the changes.

screenshot-p138

### CODE REVIEW

**Comment by andulv** [comment]
Thanks a lot for you contributions! I don't have much to work on this project at the moment, so nice to  see someone following up. :)

**Comment by Jamedjo** [comment]
Thanks for making it! Your project got a lot of love on Reddit too

**Comment by andulv** [comment]
I noticed the Reddit thread.. Never expected people to actually use (and appreciate) such a unfinished product. :)

I hope to do some refactoring / cleanup of the code the next days (if I find the time). I will try to keep in sync with your work. (My "plan" before your patches was to clean up the code, fix bugs/functionality regarding conversion from rocksmith to score and then start to add functionality).

I am quite new to cooperating on GitHub, it seems like you are a bit more experienced so feel free to correct me if I do anything stupid.

I have no plans to release an .exe / installer in the near future, so that we avoid "conflicting releases" and confusion regarding what is the current version. Maybe I should refer to your fork as the "official distribution" or something, if you will continue to building and releasing .exe for end users?

BTW: If we both continue working on this, there will propably be need for some discussions and such. Do you have any suggestions for a better forum than pull-request-comments?

**Comment by Jamedjo** [comment]
If you add me as a contributor the the project I can push changes, tag/close issues, and make releases on your project. I could probably also remove the releases from mine leaving a message pointing to your project.

Would it be ok if we stuck to the changes on my .net 4.0 branch so I can continue using VS 2010? Although I've just ordered a bigger SSD to so I can install a later version.

Also I managed to get AlphaTab to work from source by compiling it in its own project and using the dll. Since alot of the variable names changed its in a separate branch Jamedjo/RSTabExplorer@a29c215c5

**Comment by Jamedjo** [comment]
Ok, I've added the releases. Easier than I expected as created them when I pushed the tags from my fork.

**Comment by andulv** [comment]
I've sent you an email.

**Pull request merged**
